repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.13.4
    hooks:
      - id: pymarkdown
  - repo: https://github.com/tom65536/pre-commit-v
    rev: v0.2.0
    hooks:
      - id: v-vet
      - id: v-fmt
      - id: v-test
